language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

env:
  global:
    - RUSTFLAGS="-D warnings"
  jobs:
    - GRAPHICAL_BACKEND=metal
    - GRAPHICAL_BACKEND=vulkan

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  exclude:
    - os: linux
      env: GRAPHICAL_BACKEND=metal
    - os: osx
      env: GRAPHICAL_BACKEND=vulkan
    - os: windows
      env: GRAPHICAL_BACKEND=metal

branches:
  only:
    - staging
    - trying
    - master

before_install:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo fmt --verbose -- --verbose --check
  - cargo clippy --verbose --features $GRAPHICAL_BACKEND
  - cargo build --verbose --features $GRAPHICAL_BACKEND
  - cargo test --verbose --features $GRAPHICAL_BACKEND

addons:
  apt:
    update: true
    packages:
      - libasound2-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
