language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

env:
  jobs:
    - GRAPHICAL_BACKEND=metal
    - GRAPHICAL_BACKEND=vulkan

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  exclude:
    - os: linux
      env: GRAPHICAL_BACKEND=metal
    - os: osx
      env: GRAPHICAL_BACKEND=vulkan
    - os: windows
      env: GRAPHICAL_BACKEND=metal

branches:
  only:
    - staging
    - trying
    - master

before_install:
  - rustup +stable component add clippy
  - rustup +nightly-2020-03-22 component add rustfmt

script:
  - ./inspector fmt-check
  - ./inspector clippy
  - ./inspector build
  - ./inspector test

addons:
  apt:
    update: true
    packages:
      - libasound2-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev

git:
  autocrlf: input
